### ISSUE TITLE
dev-* references should update pinned commit in composer.lock

### ISSUE THREAD

**Issue by felixfbecker** [dependencies-io/collector-php-composer#14]
When having a dependency on `dev-master`, the commit hash should be updated in composer.lock if there is a new commit available.

Example: https://app.dependencies.io/projects/github/felixfbecker/vscode-php-intellisense/builds/30

Name | Path | Source | Installed | Found | Actions
-- | -- | -- | -- | -- | --
jetbrains/phpstorm-stubs | / | packagist | `dev-master` | 1 versions | -

**Comment by davegaeddert** [comment]
I'll try and look into this a little bit. Let me know if you have more specific thoughts on how to handle it.
